### PR TITLE
Change image output format from PPM to PNG

### PR DESCRIPTION
**Pull request by zephyr**

### CODE REVIEW

**Comment by markphelps** [comment]
Thanks for the PR! This is awesome! I was hoping to add PNG support

One issue, when I'm trying to build I get the following:
```
$ go build
# github.com/zephyr/go-trace
./main.go:84: rgb.Sqrt undefined (type primitives.Color has no field or method Sqrt)
```

Any idea what would cause this? I can clearly see that you added a Sqrt() method to Color

**Comment by BinaryPaean** [comment]
I come from reddit.

My guess is the problem has to do with the way you qualified your import in main.go:14. That version of "color" probably doesn't include the PR changes, and thus does _not_ have the addition of the Sqrt() method included.

**Comment by markphelps** [comment]
@BinaryPaean you are 100% correct. didn't even think of that. updated the import to point to @zephyr 's version and it worked.

Thanks!

**Comment by zephyr** [comment]
That’ll work, but has it’s own problems.

If you say `go build` somewhere in your $GOPATH, Go will use the files from the local folders (which are derived from their URLs). So if you forget to change your import statement back, and later change something in `primitives`, you’ll wonder why your changes will have no effect! (because it’ll use the my fork, which will not have your new modifications).

The simplest solution would be of course to just merge this pull request (oh, you just done it ;).

But next time you want to inspect / build a Go pull request from someone, you can do it ›the Git way‹: Instead of

`git clone https://github.com/zephyr/go-trace`
use
`git remote add zephyr https://github.com/zephyr/go-trace`

Than you can look locally at the diff (`git diff master zephyr/master) or build it locally:
`git checkout zephyr/master`
`go build`
Just don't forget to `git checkout master; git pull` after you accepted the pull request on Github.

**Pull request merged**
